### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by Ravinder2526** [GRIFFINCollaboration/detectorSimulations#102]
I am continuously getting the error of undefined refrence .
[100%] Linking CXX executable sim
/usr/bin/ld: CMakeFiles/sim.dir/sim.cc.o: in function `main':
sim.cc:(.text.startup+0x14d): undefined reference to `MyDetectorConstruction::MyDetectorConstruction()'
/usr/bin/ld: sim.cc:(.text.startup+0x178): undefined reference to `MyPhysicsList::MyPhysicsList()'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/sim.dir/build.make:124: sim] Error 1
make[1]: *** [CMakeFiles/Makefile2:104: CMakeFiles/sim.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by VinzenzBildstein** [comment]
sim.cc (the file that creates that error) does not exist anywhere in this repository?
