### ISSUE TITLE
Issue with Qt visualisation 

### ISSUE THREAD

**Issue by carlu** [GRIFFINCollaboration/detectorSimulations#24]
Hi folks.  So of all the visualisation options, I think the Qt one is the best for quick debugging issues.   Mainly just because you can rotate, zoom, scroll etc with the mouse, and change run options from the gui without needing to re-write a run macro.

When I use this visualisation on the GEANT4 examples I get a nice "scene-tree" containing a list of all the physical volumes which I can switch on and off.  In our code however I can't see this list.  I've been trying to figure out why but I've so far failed.  Let me know if you have any ideas, otherwise I'll update this issue when I manage to fix it.  For now I'm going to look at something else....

(See screenshots below....)

![temp](https://f.cloud.github.com/assets/660775/1127600/0595596c-1b40-11e3-86f0-0d85c541d010.png)
![temp1](https://f.cloud.github.com/assets/660775/1127603/0ab9bcb2-1b40-11e3-939b-3d8eb44df9d9.png)

**Comment by jacquesdoumani** [comment]
hello, some geant4 ex have some extra commands added on the top of the viewer that can be an easier way to run a beam or..
they are listed as: File Run Gun Vis Viewer
my problem is that i was working on a CADm
![screenshot from 2017-07-21 11-14-01](https://user-images.githubusercontent.com/30294855/28472430-2c2f5ed4-6e06-11e7-9253-fc871e6230d0.png)
![screenshot from 2017-07-21 11-14-18](https://user-images.githubusercontent.com/30294855/28472431-2c30bd24-6e06-11e7-8e03-76b087d7ecac.png)

esh ex and they didn't appear, i will attach 2 photos for both ex with and without.
anyone know's how to add these commands and the location where they should be added. Thanks!
